<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_mailbioskoponlinegmail.com</name>
   <tag></tag>
   <elementGuidId>2f87d730-965b-4353-a59c-d8e95cc5e314</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jBjuwf']/span/div/div/span/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span > div.PrDSKc > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>72ed66cd-3d25-4141-bbdb-4af09d9721c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:mailbioskoponline@gmail.com</value>
      <webElementGuid>ae433409-3324-4708-ba8b-8030330dae05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>426a767d-a31f-468a-81cf-18d969fe4726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mailbioskoponline@gmail.com</value>
      <webElementGuid>99a9e68d-694d-45f6-a8bc-2f2a30b68ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jBjuwf&quot;)/span[@class=&quot;PbnGhe oJeWuf fb0g6&quot;]/div[1]/div[1]/span[1]/div[@class=&quot;PrDSKc&quot;]/a[1]</value>
      <webElementGuid>faab1e0b-dc9a-4db9-a74c-dcb6d2314d13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jBjuwf']/span/div/div/span/div/a</value>
      <webElementGuid>c1271166-cdab-4f8b-876d-e40d9036c00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'mailbioskoponline@gmail.com')]</value>
      <webElementGuid>cb1deb69-0c34-4651-8ac1-c851ff2d4451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oke'])[1]/following::a[1]</value>
      <webElementGuid>bda118d3-dfe4-42c3-93c6-0a3068440bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setelah masuk, Anda akan dialihkan ke: https://bioskoponline.com'])[1]/preceding::a[1]</value>
      <webElementGuid>bc649fe5-6cae-4515-94ac-f6ba23464e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oke'])[2]/preceding::a[1]</value>
      <webElementGuid>76cf8dfd-2283-41b8-847b-36c999b44ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='mailbioskoponline@gmail.com']/parent::*</value>
      <webElementGuid>5f59cb53-cd8b-4da9-a95d-dfa9bce8f200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'mailto:mailbioskoponline@gmail.com')]</value>
      <webElementGuid>1dab05dd-c4e6-4241-b553-f5bce90ebd0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/a</value>
      <webElementGuid>3e27c90a-0bd0-43f6-868b-d06ab354d2c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'mailto:mailbioskoponline@gmail.com' and (text() = 'mailbioskoponline@gmail.com' or . = 'mailbioskoponline@gmail.com')]</value>
      <webElementGuid>a63b1f71-1325-4d41-a4a0-8f5ed1eddfe8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
