<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Not now</name>
   <tag></tag>
   <elementGuidId>359e6a03-f3ef-4547-ac14-f0babe53c860</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div[2]/div[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span._2iem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f91b74ba-cd90-404f-8d88-547a116baa76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2iem</value>
      <webElementGuid>670b1c9b-55f1-403e-b330-8e8c5ae2eb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not now</value>
      <webElementGuid>3b96e7e4-abdd-469d-94ef-c559d4acfbe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;_4-u5 _30ny&quot;]/div[@class=&quot;_4-u2 _1w1t _4-u8 _52jv&quot;]/div[2]/div[2]/a[@class=&quot;_97w6&quot;]/span[@class=&quot;_2iem&quot;]</value>
      <webElementGuid>237e92de-3003-4af1-8b59-70f023ac226e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div[2]/div[2]/a/span</value>
      <webElementGuid>52bcc447-1530-4cad-881a-95188b21e723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error Accessing App'])[1]/following::span[1]</value>
      <webElementGuid>e12e6620-3187-4aa5-a7f7-b4bb8d87e265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in to Facebook'])[1]/following::span[1]</value>
      <webElementGuid>30ec97e8-3ac9-4e2b-b025-596c3885fc41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English (UK)'])[1]/preceding::span[1]</value>
      <webElementGuid>c860186b-4dc7-4655-ba19-8f93961db88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa Indonesia'])[1]/preceding::span[1]</value>
      <webElementGuid>1a97b4c1-078a-4b2b-9a6f-be2112333422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Not now']/parent::*</value>
      <webElementGuid>08e65b34-40e9-49c5-a276-0f3c7b897eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>166b49f6-aa34-4b00-98e6-c29f0c53cb78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Not now' or . = 'Not now')]</value>
      <webElementGuid>8af643fe-0fa2-44bd-b745-edd7d60411f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
