<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_bioskoponline.com</name>
   <tag></tag>
   <elementGuidId>b5cb6025-6002-474b-82c0-3c3d4dc96a97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[type=&quot;button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e329c46a-d986-48de-a7b7-e4cbfcc10ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jscontroller</name>
      <type>Main</type>
      <value>QOLEBb</value>
      <webElementGuid>c107bea8-e0bb-466e-8a97-062ff284dfb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>487cc011-ff97-4dfc-9d4f-9ea861a96ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>LZaERc</value>
      <webElementGuid>016315b1-2c0f-428d-bd6e-28cd06222468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>click:CnOdef(preventDefault=true)</value>
      <webElementGuid>5493d9e9-3061-4cf2-b78b-9768a2bf2884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-destination-info</name>
      <type>Main</type>
      <value>Setelah masuk, Anda akan dialihkan ke: https://bioskoponline.com</value>
      <webElementGuid>05674397-cb17-49cf-889d-49d3c2889a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-third-party-email</name>
      <type>Main</type>
      <value>mailbioskoponline@gmail.com</value>
      <webElementGuid>89da1385-511a-4a7a-af2f-01ae5705fd07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bioskoponline.com</value>
      <webElementGuid>7edcefd4-85cd-405f-ab8e-4de553c16cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headingSubtext&quot;)/span[1]/button[1]</value>
      <webElementGuid>4cdc9ec4-bbb5-4b0e-b109-66eff4bd1473</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>935bbc29-0325-43ea-bcca-0dec906231f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headingSubtext']/span/button</value>
      <webElementGuid>f4f5d467-3988-48bc-aa9f-15847d674205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::button[1]</value>
      <webElementGuid>297c882f-e661-4d24-9cfe-715f823e8f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa email?'])[1]/preceding::button[1]</value>
      <webElementGuid>c3e61165-0617-4b75-99b0-14f610019216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kebijakan privasi'])[1]/preceding::button[3]</value>
      <webElementGuid>7d82976a-598b-406f-9869-559d8c1f4cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='bioskoponline.com']/parent::*</value>
      <webElementGuid>cd6f0602-9605-4526-b218-52844cfff443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0fee170c-db18-4349-b86a-f7fb18d03ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'bioskoponline.com' or . = 'bioskoponline.com')]</value>
      <webElementGuid>057087af-f855-42d8-a6e1-9417cad2438d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
