<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Login dengan Google</name>
   <tag></tag>
   <elementGuidId>559673dd-4286-4a6e-a07b-2c8f41c1902c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='initialView']/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>195fb11e-e890-4e85-a131-37b49749737a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Lth2jb </value>
      <webElementGuid>7e0b1df3-5335-48ae-ab0f-1a49daeda933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>n7vHCb</value>
      <webElementGuid>7c74b081-c6cb-416b-94bd-aaca317018e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jscontroller</name>
      <type>Main</type>
      <value>rKxYMb</value>
      <webElementGuid>ed27eb69-0bf1-43ae-8528-0b30c4dfd083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>rcuQ6b:qg4Ic;Kzwjs:WPi0i;</value>
      <webElementGuid>69e94afa-ecca-4c84-9d37-5828ec4a848b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login dengan Google</value>
      <webElementGuid>e144fc14-4308-445a-b79b-034740cc8a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;initialView&quot;)/div[@class=&quot;xkfVF&quot;]/div[@class=&quot;Aa1VU&quot;]/div[@class=&quot;Lth2jb&quot;]</value>
      <webElementGuid>d0de75eb-5136-4e10-b0ec-6b8233d7e031</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='initialView']/div[2]/div/div</value>
      <webElementGuid>b7a4a827-5778-4a0e-b445-9dc5879c42b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak dapat membuat Anda login'])[1]/preceding::div[4]</value>
      <webElementGuid>ef2d10ef-7e3f-4b01-a446-e4195c200375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>81279480-9fac-4e47-a3e7-f99747fd2cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Login dengan Google' or . = 'Login dengan Google')]</value>
      <webElementGuid>13e6580a-a86c-4bee-a77a-3a31cacc9148</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
