<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Info pengembang</name>
   <tag></tag>
   <elementGuidId>b62e24b4-0755-4273-966b-1381d40ea50f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dwrFZd0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dwrFZd0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>27e3d520-d53b-477f-b9ef-6ff961751f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>YASyvd</value>
      <webElementGuid>77f360e7-e056-41f5-bf0a-fad38b28bed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PNenzf</value>
      <webElementGuid>8b86b540-a186-4578-a2e0-af2999eccaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>18b56761-3175-4fd8-95cd-eb5b8f4905ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0e7b90fa-a5b4-441d-b13c-e93f88a6b0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dwrFZd0</value>
      <webElementGuid>ef3b0a5e-b280-4cb9-97df-1e540cd5576f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Info pengembang</value>
      <webElementGuid>5dba9600-62d7-4b48-94fc-c69b5c48b75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dwrFZd0&quot;)</value>
      <webElementGuid>a349bfee-bd60-4aa7-9b50-8bfcf2390015</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dwrFZd0']</value>
      <webElementGuid>214712f6-61f7-4eb3-b1ec-0ba8437db9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jBjuwf']/div[2]/div</value>
      <webElementGuid>26beef40-d9c0-4151-9756-8f4a234e9b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'dwrFZd0', '&quot;', ')')])[1]/following::div[7]</value>
      <webElementGuid>437c1113-b4bf-4c69-801a-32043712e3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login Lanjutkan ke bioskoponline.com'])[1]/following::div[9]</value>
      <webElementGuid>31639463-7c74-4586-a635-2c099b5d74a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oke'])[1]/preceding::div[3]</value>
      <webElementGuid>2b4d8cd4-c047-4cfb-a864-7bd7a03f6094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Info pengembang']/parent::*</value>
      <webElementGuid>6688f3a2-518d-459e-9f57-939a45ba571c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>034680d1-6dc7-4fbc-9a84-305b4ffff4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dwrFZd0' and (text() = 'Info pengembang' or . = 'Info pengembang')]</value>
      <webElementGuid>0b5e9884-fe86-4634-b765-87859b93f5fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
