<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Error Accessing App</name>
   <tag></tag>
   <elementGuidId>1428a9ab-3364-43ae-be12-b592ec436936</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fb_logo.img.sp_Awgqz7K4lHq.sx_55d19b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/div[1]/div/div/div[2]/div[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7012cc2f-82a4-46f4-bb93-33046e077e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fb_logo img sp_Awgqz7K4lHq sx_55d19b</value>
      <webElementGuid>777bfde5-a471-485b-81c4-b442174b1539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Facebook</value>
      <webElementGuid>80a0fe65-345f-4629-a3fe-b92848d44f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blueBarDOMInspector&quot;)/div[@class=&quot;_53jh&quot;]/div[@class=&quot;loggedout_menubar_container&quot;]/div[@class=&quot;clearfix loggedout_menubar&quot;]/div[@class=&quot;lfloat _ohe&quot;]/h1[1]/a[1]/i[@class=&quot;fb_logo img sp_Awgqz7K4lHq sx_55d19b&quot;]</value>
      <webElementGuid>16364404-e290-4e3c-86c0-59a043d60809</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='blueBarDOMInspector']/div/div/div/div/h1/a/i</value>
      <webElementGuid>bd5cbe8c-8478-409d-b5b3-f8eb7f9da23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New Account'])[1]/preceding::i[1]</value>
      <webElementGuid>624795a6-13e5-4cb5-b073-f0c1cf7f0090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>0b0f79c7-b720-4f7c-aac4-46cd14327899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'Facebook' or . = 'Facebook')]</value>
      <webElementGuid>45fc8dce-8bb9-423f-8842-0cb4de4b1aa3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
