<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Oke</name>
   <tag></tag>
   <elementGuidId>291edab8-75eb-4752-8278-9d41eb441217</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jBjuwf']/div[3]/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.U26fgb.O0WRkf.oG5Srb.C0oVfc.kHssdc.lw1w4b.M9Bg4d.qs41qe > span.CwaK9 > span.RveJvd.snByac</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2ed25fc4-1951-4a24-8562-664ff15fb425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RveJvd snByac</value>
      <webElementGuid>da73b999-3c5f-4bbc-a30f-8fc747a80a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oke</value>
      <webElementGuid>9fabbda8-7a0a-4cef-bfd8-6910b30011b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jBjuwf&quot;)/div[@class=&quot;XfpsVe J9fJmf&quot;]/div[@class=&quot;U26fgb O0WRkf oG5Srb C0oVfc kHssdc lw1w4b M9Bg4d qs41qe&quot;]/span[@class=&quot;CwaK9&quot;]/span[@class=&quot;RveJvd snByac&quot;]</value>
      <webElementGuid>d601e85e-a3ff-4bfe-b41c-9a67d7847f53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jBjuwf']/div[3]/div/span/span</value>
      <webElementGuid>18cf1a23-b611-46b9-b3a2-eb3fc3581bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setelah masuk, Anda akan dialihkan ke: https://bioskoponline.com'])[1]/following::span[2]</value>
      <webElementGuid>ca0967cb-6f9f-4348-8d78-3a11ef5cd7b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mailbioskoponline@gmail.com'])[1]/following::span[2]</value>
      <webElementGuid>3e0211cd-e4ca-449f-8a84-53c3b557f0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/span</value>
      <webElementGuid>a0ac4a36-d5fa-450e-8b39-4aac3ba9276a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Oke' or . = 'Oke')]</value>
      <webElementGuid>66ee350a-9d18-40b4-b49f-c3a898c7f0a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
